[package]
name = "CutListOptimizer1D"
version = "0.1.0"
edition = "2021"

[dependencies]
cut-optimizer-1d = { version = "0.2.2", path = "libs/cut-optimizer-1d" }
gumdrop = "0.8"
json = "0.12.4"
rand = "0.9.0"
rayon = "1.10.0"

